# Open Chat 테스트

### value
@accessToken = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJwZXRtaWx5IiwiaWF0IjoxNzI0ODM0NDgyLCJleHAiOjE3MjQ4MzgwODIsInN1YiI6ImtpbWp1bjkxIn0.Oz_FySP0Gs2-McZhPafQGS1ct713B-HrLVnJuczuqBw
#@accessToken = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJwZXRtaWx5IiwiaWF0IjoxNzI0NjU1NjY1LCJleHAiOjE3MjQ2NTkyNjUsInN1YiI6ImtpbWp1bjkxIn0.vzP2LGmGYTiq72O4Y5PNKrVJj3Y3RdM3DM74MTC0Tug

### 회원1 로그인 요청
POST http://localhost:8080/api/v1/users/login
Content-Type: application/json

{
  "username": "kimjun91",
  "password": "kim123"
}

### 오픈채팅 생성
POST http://localhost:8080/api/v1/open-chats
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "categoryId": 3,
  "title": "OO동 오후 7시 산책 하실 분",
  "description":"대화하면서 산책하실 분 모집합니다.",
  "password": null,
  "maxParticipants": 5,
  "isPublic": true
}

### 오픈채팅 목록 조회
GET http://localhost:8080/api/v1/open-chats?page=0&size=10
Authorization: Bearer {{accessToken}}

### 오픈채팅 정보 조회
GET http://localhost:8080/api/v1/open-chats/2
Authorization: Bearer {{accessToken}}