# post 테스트

### 게시물 등록
POST http://localhost:8080/api/v1/posts
Content-Type: application/json

{
  "userId": 1,
  "categoryId": 1,
  "thumbnailPath": "abc",
  "title": "abc",
  "content": "abc",
  "imagePath": "abc",
  "postStatus": "PUBLIC"
}

### 게시물 전체 조회 (카테고리별)
GET http://localhost:8080/api/v1/posts?categoryId=1&page=0&size=5
Content-Type: application/json

### 게시물 정보 조회
GET http://localhost:8080/api/v1/posts/1
Content-Type: application/json

### 게시물 수정
PUT http://localhost:8080/api/v1/posts/1
Content-Type: application/json

{
  "userId": 1,
  "categoryId": 3,
  "thumbnailPath": "abcd",
  "title": "abcd",
  "content": "abcd",
  "imagePath": "abcd",
  "postStatus": "PUBLIC"
}

### 게시물 삭제
DELETE http://localhost:8080/api/v1/posts/1
Content-Type: application/json


# comment 테스트
### 댓글 등록
POST http://localhost:8080/api/v1/posts/1/comment
Content-Type: application/json

{
  "userId": 1,
  "parentId": null,
  "content": "댓글등록"
}

### 댓글 수정
PUT http://localhost:8080/api/v1/posts/comment/1
Content-Type: application/json

{
  "userId": 2,
  "parentId": null,
  "content": "댓글수정"
}

### 댓글 삭제
DELETE http://localhost:8080/api/v1/posts/comment/1
Content-Type: application/json


# likes 테스트
### 좋아요 등록
POST http://localhost:8080/api/vi/posts/likes
Content-Type: application/json

{
  "userId": 1,
  "postId": 1
}

### 좋아요 삭제
DELETE http://localhost:8080/api/vi/posts/likes
Content-Type: application/json

{
  "userId": 1,
  "postId": 1
}
