# post 테스트

### value
@accessToken = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJwZXRtaWx5IiwiaWF0IjoxNzI0OTM5OTcxLCJleHAiOjE3MjQ5NDM1NzEsInN1YiI6ImFkbWluIn0.9JXPnaBSLPttCcSabAtyMKyXfqbAamAwu0mTY3M8k84

### 회원1 로그인 요청
POST http://localhost:8080/api/v1/users/login
Content-Type: application/json

{
  "username": "kimjun91",
  "password": "kim123"
}

### 관리자 로그인 요청
POST http://localhost:8080/api/v1/users/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}


### 게시물 등록
POST http://localhost:8080/api/v1/posts
Authorization: Bearer {{accessToken}}
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="dto"
Content-type: application/json

{
  "categoryId": 1,
  "title": "before",
  "content": "before",
  "hashtagNames": ["#강아지", "#사료"],
  "postStatus": "PUBLIC"
}

#--boundary
#Content-Disposition: form-data; name="files"; filename="image1.png"
#Content-Type: image/png
#
#C:\\image1.png
#
#--boundary
#Content-Disposition: form-data; name="files"; filename="image2.png"
#Content-Type: image/png
#
#C:\\image2.png

--boundary--

### 게시물 전체 조회 (카테고리별)
GET http://localhost:8080/api/v1/posts?categoryId=1&page=0&size=5
Authorization: Bearer {{accessToken}}
Content-Type: application/json

### 게시물 전체 조회 (해시태그별)
GET http://localhost:8080/api/v1/posts?hashtagName=#강아지&page=0&size=5
Authorization: Bearer {{accessToken}}
Content-Type: application/json

### 게시물 전체 조회 (카테고리 & 해시태그별)
GET http://localhost:8080/api/v1/posts?categoryId=1&hashtagName=#강아지&page=0&size=5
Authorization: Bearer {{accessToken}}
Content-Type: application/json

### 게시물 정보 조회
GET http://localhost:8080/api/v1/posts/1
Authorization: Bearer {{accessToken}}
Content-Type: application/json

### 게시물 수정
PUT http://localhost:8080/api/v1/posts/1
Authorization: Bearer {{accessToken}}
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="dto"
Content-type: application/json

{
  "categoryId": 3,
  "title": "after",
  "content": "after",
  "hashtagNames": ["#고양이", "#사료"],
  "postStatus": "PUBLIC"
}

#--boundary
#Content-Disposition: form-data; name="files"; filename="image1.png"
#Content-Type: image/png
#
#C:\\image1.png

--boundary--

### 게시물 삭제
DELETE http://localhost:8080/api/v1/posts/1
Authorization: Bearer {{accessToken}}
Content-Type: application/json

### 전체 해시태그 조회
GET http://localhost:8080/api/v1/posts/hashtags
Authorization: Bearer {{accessToken}}
Content-Type: application/json

### 해시태그 추가 (관리자 전용)
POST http://localhost:8080/api/v1/posts/hashtags
Authorization: Bearer {{accessToken}}
Content-Type: application/json

["#동물", "#장난감"]

### 게시물 카테고리 수정 (관리자 전용)
PUT http://localhost:8080/api/v1/posts/category/2
Authorization: Bearer {{accessToken}}
Content-Type: application/json

7

### 댓글 등록
POST http://localhost:8080/api/v1/posts/1/comment
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "parentId": null,
  "content": "댓글등록"
}

### 댓글 수정
PUT http://localhost:8080/api/v1/posts/comment/1
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "parentId": null,
  "content": "댓글수정"
}

### 댓글 삭제
DELETE http://localhost:8080/api/v1/posts/comment/1
Authorization: Bearer {{accessToken}}
Content-Type: application/json



### 좋아요 등록
POST http://localhost:8080/api/vi/posts/likes/1
Authorization: Bearer {{accessToken}}
Content-Type: application/json

### 좋아요 삭제
DELETE http://localhost:8080/api/vi/posts/likes/1
Authorization: Bearer {{accessToken}}
Content-Type: application/json
