### 회원가입 요청 - 회원1
# @no-redirect
POST http://localhost:8080/api/v1/users/signup
Content-Type: application/json

{
  "username": "test91",
  "email": "test91.jun@example.com",
  "password": "lee123",
  "address": "강원특별자치도 양양군",
  "age": 33,
  "birthDate": "1991-11-11",
  "gender": "M",
  "name": "김준",
  "nickname": "감자",
  "phone": "010-1234-8765"
}

### 로그인 요청
POST http://localhost:8080/api/v1/users/login
Content-Type: application/json

{
  "username": "kimjun91",
  "password": "kim123"
}

### 로그아웃 요청 (토큰 필요)
POST http://localhost:8080/api/v1/users/logout
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJwZXRtaWx5IiwiaWF0IjoxNzI0MjEyODgyLCJleHAiOjE3MjQyMTY0ODIsInN1YiI6InBhcmtoeXVuODkifQ.Jpl6AxPH7nVBtMRkAw7zgXTOlyuXW9dZe_Qpi2-Kdu4
Content-Type: application/json

{
}

### 사용자 정보 조회
# @no-redirect
GET http://localhost:8080/api/v1/users/3
Authorization: Bearer eyJ0eXAdiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJwZXRtaWx5IiwiaWF0IjoxNzI0MjEzMTUwLCJleHAiOjE3MjQyMTY3NTAsInN1YiI6ImtpbWp1bjkxIn0.f5NO0trcZvTE-ndM08PUsEpvhxVtE7oXujOq-lXhKYI
Content-Type: application/json