# Walk Goal 요청

### value
@accessToken = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJwZXRtaWx5IiwiaWF0IjoxNzI0OTM5OTcxLCJleHAiOjE3MjQ5NDM1NzEsInN1YiI6ImFkbWluIn0.9JXPnaBSLPttCcSabAtyMKyXfqbAamAwu0mTY3M8k84
@petId = 3

### 회원1 로그인 요청
POST http://localhost:8080/api/v1/users/login
Content-Type: application/json

{
  "username": "kimjun91",
  "password": "kim123"
}

### 산책 목표 설정
POST http://localhost:8080/api/v1/walks/pets/{{petId}}/goal
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "title":"매일 매일 산책하기!!",
  "dailyTargetMinutes": 30,
  "targetStartTime": "17:00"
}

### 산책 목표 조회
GET http://localhost:8080/api/v1/walks/pets/{{petId}}/goal
Authorization: Bearer {{accessToken}}
#Content-Type: application/json

### 산책 목표 수정
PUT http://localhost:8080/api/v1/walks/pets/{{petId}}/goal
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "title":"매일 매일 산책하기2!!",
  "dailyTargetMinutes": 30,
  "targetStartTime": "17:00"
}

### 산책 목표 삭제
DELETE http://localhost:8080/api/v1/walks/pets/{{petId}}/goal
Authorization: Bearer {{accessToken}}
#Content-Type: application/json